<?php

/**
 * @file
 * Contains commerce_xps.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function commerce_xps_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the commerce_xps module.
    case 'help.page.commerce_xps':
      // Todo load the readme.md
      $output = 'todo';
      return $output;
  }
}
