commerce_shipping.commerce_shipping_method.plugin.xps:
  type: commerce_shipping_method_configuration
  mapping:
    api_information:
      label: "API information"
      type: mapping
      mapping:
        api_key:
          type: string
          label: "API Key"
        customer_id:
          type: string
          label: "Customer ID"
    options:
      type: mapping
      label: "XPS Options"
      mapping:
        log:
          type: mapping
          label: "Log the following messages for debugging"
          mapping:
            request:
              type: field.value.boolean
              mapping:
                value:
                  label: "API request messages"
            response:
              type: field.value.boolean
              mapping:
                value:
                  label: "API response messages"
